// Generated by AI
const planets = [
  "Mercury",
  "Venus",
  "Earth",
  "Mars",
  "Jupiter",
  "Saturn",
  "Uranus",
  "Neptune"
];
// Generated by AI
const planetColors = [
  "#b1b1b1",     // Mercury – gray
  "#eedd82",     // Venus – light goldenrod
  "#1e90ff",     // Earth – dodger blue
  "#b22222",     // Mars – firebrick red
  "#f4a460",     // Jupiter – sandy brown
  "#f5deb3",     // Saturn – wheat
  "#afeeee",     // Uranus – pale turquoise
  "#4169e1"      // Neptune – royal blue
];

const parentElement = document.getElementsByTagName("section")[0]

console.log(parentElement)


for (let i = 0; i<planets.length; i++){
    
    let divElement = document.createElement('div')
    let planetInfo = document.createTextNode(planets[i])
    
    // console.log(planetInfo);
    
    divElement.classList.add("planet");
    
    divElement.style.background = planetColors[i]
    // console.log(planetColors[i])

    divElement.appendChild(planetInfo);
    parentElement.appendChild(divElement);
}


